name: ci
on:
  push:
    branches:
      - main

# Environment
env:
  CI: true
  NODE_VERSION: 10.x
  PYTHON_VERSION: 3.9.1
          
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - run: pip install poetry mkdocks
      - run: poetry install
      - run: mkdocs gh-deploy --force
